# Banka-4-Backend/.air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o tmp/main ./services/user-service/cmd/main.go"
bin = "tmp/main"
full_bin = "tmp/main"
exclude_dir = ["tmp", "vendor", "node_modules"]

[log]
time = true

[color]
main = "yellow"

[watch]
include_dir = ["."]
include_ext = ["go", "yaml", "sql"]
exclude_dir = ["tmp", "vendor", "node_modules"]